#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidTest.Resource", IsApplication=true)]

namespace AndroidTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int ButtonSignUpStyle = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int down = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int edit_text_style = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_down = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int slide_right = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Burger = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ZarksBurger = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int Age = 2131165195;
			
			// aapt resource value: 0x7f070042
			public const int Choices1 = 2131165250;
			
			// aapt resource value: 0x7f070077
			public const int Choices10 = 2131165303;
			
			// aapt resource value: 0x7f07007c
			public const int Choices11 = 2131165308;
			
			// aapt resource value: 0x7f070082
			public const int Choices12 = 2131165314;
			
			// aapt resource value: 0x7f070087
			public const int Choices13 = 2131165319;
			
			// aapt resource value: 0x7f07008c
			public const int Choices14 = 2131165324;
			
			// aapt resource value: 0x7f070091
			public const int Choices15 = 2131165329;
			
			// aapt resource value: 0x7f070098
			public const int Choices16 = 2131165336;
			
			// aapt resource value: 0x7f070048
			public const int Choices2 = 2131165256;
			
			// aapt resource value: 0x7f070017
			public const int Choices24 = 2131165207;
			
			// aapt resource value: 0x7f07001c
			public const int Choices25 = 2131165212;
			
			// aapt resource value: 0x7f070023
			public const int Choices26 = 2131165219;
			
			// aapt resource value: 0x7f070028
			public const int Choices27 = 2131165224;
			
			// aapt resource value: 0x7f07002f
			public const int Choices28 = 2131165231;
			
			// aapt resource value: 0x7f070036
			public const int Choices29 = 2131165238;
			
			// aapt resource value: 0x7f07004f
			public const int Choices3 = 2131165263;
			
			// aapt resource value: 0x7f07003d
			public const int Choices30 = 2131165245;
			
			// aapt resource value: 0x7f070055
			public const int Choices4 = 2131165269;
			
			// aapt resource value: 0x7f07005c
			public const int Choices5 = 2131165276;
			
			// aapt resource value: 0x7f070061
			public const int Choices6 = 2131165281;
			
			// aapt resource value: 0x7f070068
			public const int Choices7 = 2131165288;
			
			// aapt resource value: 0x7f07006d
			public const int Choices8 = 2131165293;
			
			// aapt resource value: 0x7f070072
			public const int Choices9 = 2131165298;
			
			// aapt resource value: 0x7f07009f
			public const int Edit_Quest17 = 2131165343;
			
			// aapt resource value: 0x7f0700a1
			public const int Edit_Quest18 = 2131165345;
			
			// aapt resource value: 0x7f0700a3
			public const int Edit_Quest19 = 2131165347;
			
			// aapt resource value: 0x7f0700a5
			public const int Edit_Quest20 = 2131165349;
			
			// aapt resource value: 0x7f070011
			public const int Edit_Quest21 = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int Edit_Quest22 = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int Edit_Quest23 = 2131165205;
			
			// aapt resource value: 0x7f07000a
			public const int Name = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int Proc = 2131165199;
			
			// aapt resource value: 0x7f0700a6
			public const int Proc2 = 2131165350;
			
			// aapt resource value: 0x7f0700a7
			public const int Proc3 = 2131165351;
			
			// aapt resource value: 0x7f070040
			public const int Proc4 = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int Quest1 = 2131165249;
			
			// aapt resource value: 0x7f070076
			public const int Quest10 = 2131165302;
			
			// aapt resource value: 0x7f07007b
			public const int Quest11 = 2131165307;
			
			// aapt resource value: 0x7f070081
			public const int Quest12 = 2131165313;
			
			// aapt resource value: 0x7f070086
			public const int Quest13 = 2131165318;
			
			// aapt resource value: 0x7f07008b
			public const int Quest14 = 2131165323;
			
			// aapt resource value: 0x7f070090
			public const int Quest15 = 2131165328;
			
			// aapt resource value: 0x7f070097
			public const int Quest16 = 2131165335;
			
			// aapt resource value: 0x7f07009e
			public const int Quest17 = 2131165342;
			
			// aapt resource value: 0x7f0700a0
			public const int Quest18 = 2131165344;
			
			// aapt resource value: 0x7f0700a2
			public const int Quest19 = 2131165346;
			
			// aapt resource value: 0x7f070047
			public const int Quest2 = 2131165255;
			
			// aapt resource value: 0x7f0700a4
			public const int Quest20 = 2131165348;
			
			// aapt resource value: 0x7f070010
			public const int Quest21 = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int Quest22 = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int Quest23 = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int Quest24 = 2131165206;
			
			// aapt resource value: 0x7f07001b
			public const int Quest25 = 2131165211;
			
			// aapt resource value: 0x7f070022
			public const int Quest26 = 2131165218;
			
			// aapt resource value: 0x7f070027
			public const int Quest27 = 2131165223;
			
			// aapt resource value: 0x7f07002e
			public const int Quest28 = 2131165230;
			
			// aapt resource value: 0x7f070035
			public const int Quest29 = 2131165237;
			
			// aapt resource value: 0x7f07004e
			public const int Quest3 = 2131165262;
			
			// aapt resource value: 0x7f07003c
			public const int Quest30 = 2131165244;
			
			// aapt resource value: 0x7f070054
			public const int Quest4 = 2131165268;
			
			// aapt resource value: 0x7f07005b
			public const int Quest5 = 2131165275;
			
			// aapt resource value: 0x7f070060
			public const int Quest6 = 2131165280;
			
			// aapt resource value: 0x7f070067
			public const int Quest7 = 2131165287;
			
			// aapt resource value: 0x7f07006c
			public const int Quest8 = 2131165292;
			
			// aapt resource value: 0x7f070071
			public const int Quest9 = 2131165297;
			
			// aapt resource value: 0x7f070005
			public const int Satisfaction = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int Survey = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int Welcome = 2131165188;
			
			// aapt resource value: 0x7f070043
			public const int a = 2131165251;
			
			// aapt resource value: 0x7f070078
			public const int a10 = 2131165304;
			
			// aapt resource value: 0x7f07007d
			public const int a11 = 2131165309;
			
			// aapt resource value: 0x7f070083
			public const int a12 = 2131165315;
			
			// aapt resource value: 0x7f070088
			public const int a13 = 2131165320;
			
			// aapt resource value: 0x7f07008d
			public const int a14 = 2131165325;
			
			// aapt resource value: 0x7f070092
			public const int a15 = 2131165330;
			
			// aapt resource value: 0x7f070099
			public const int a16 = 2131165337;
			
			// aapt resource value: 0x7f070049
			public const int a2 = 2131165257;
			
			// aapt resource value: 0x7f070018
			public const int a24 = 2131165208;
			
			// aapt resource value: 0x7f07001d
			public const int a25 = 2131165213;
			
			// aapt resource value: 0x7f070024
			public const int a26 = 2131165220;
			
			// aapt resource value: 0x7f070029
			public const int a27 = 2131165225;
			
			// aapt resource value: 0x7f070030
			public const int a28 = 2131165232;
			
			// aapt resource value: 0x7f070037
			public const int a29 = 2131165239;
			
			// aapt resource value: 0x7f070050
			public const int a3 = 2131165264;
			
			// aapt resource value: 0x7f07003e
			public const int a30 = 2131165246;
			
			// aapt resource value: 0x7f070056
			public const int a4 = 2131165270;
			
			// aapt resource value: 0x7f07005d
			public const int a5 = 2131165277;
			
			// aapt resource value: 0x7f070062
			public const int a6 = 2131165282;
			
			// aapt resource value: 0x7f070069
			public const int a7 = 2131165289;
			
			// aapt resource value: 0x7f07006e
			public const int a8 = 2131165294;
			
			// aapt resource value: 0x7f070073
			public const int a9 = 2131165299;
			
			// aapt resource value: 0x7f070044
			public const int b = 2131165252;
			
			// aapt resource value: 0x7f070079
			public const int b10 = 2131165305;
			
			// aapt resource value: 0x7f07007e
			public const int b11 = 2131165310;
			
			// aapt resource value: 0x7f070084
			public const int b12 = 2131165316;
			
			// aapt resource value: 0x7f070089
			public const int b13 = 2131165321;
			
			// aapt resource value: 0x7f07008e
			public const int b14 = 2131165326;
			
			// aapt resource value: 0x7f070093
			public const int b15 = 2131165331;
			
			// aapt resource value: 0x7f07009a
			public const int b16 = 2131165338;
			
			// aapt resource value: 0x7f07004a
			public const int b2 = 2131165258;
			
			// aapt resource value: 0x7f070019
			public const int b24 = 2131165209;
			
			// aapt resource value: 0x7f07001e
			public const int b25 = 2131165214;
			
			// aapt resource value: 0x7f070025
			public const int b26 = 2131165221;
			
			// aapt resource value: 0x7f07002a
			public const int b27 = 2131165226;
			
			// aapt resource value: 0x7f070031
			public const int b28 = 2131165233;
			
			// aapt resource value: 0x7f070038
			public const int b29 = 2131165240;
			
			// aapt resource value: 0x7f070051
			public const int b3 = 2131165265;
			
			// aapt resource value: 0x7f07003f
			public const int b30 = 2131165247;
			
			// aapt resource value: 0x7f070057
			public const int b4 = 2131165271;
			
			// aapt resource value: 0x7f07005e
			public const int b5 = 2131165278;
			
			// aapt resource value: 0x7f070063
			public const int b6 = 2131165283;
			
			// aapt resource value: 0x7f07006a
			public const int b7 = 2131165290;
			
			// aapt resource value: 0x7f07006f
			public const int b8 = 2131165295;
			
			// aapt resource value: 0x7f070074
			public const int b9 = 2131165300;
			
			// aapt resource value: 0x7f070008
			public const int btnGetStarted = 2131165192;
			
			// aapt resource value: 0x7f070045
			public const int c = 2131165253;
			
			// aapt resource value: 0x7f07007a
			public const int c10 = 2131165306;
			
			// aapt resource value: 0x7f07007f
			public const int c11 = 2131165311;
			
			// aapt resource value: 0x7f070085
			public const int c12 = 2131165317;
			
			// aapt resource value: 0x7f07008a
			public const int c13 = 2131165322;
			
			// aapt resource value: 0x7f07008f
			public const int c14 = 2131165327;
			
			// aapt resource value: 0x7f070094
			public const int c15 = 2131165332;
			
			// aapt resource value: 0x7f07009b
			public const int c16 = 2131165339;
			
			// aapt resource value: 0x7f07004b
			public const int c2 = 2131165259;
			
			// aapt resource value: 0x7f07001a
			public const int c24 = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int c25 = 2131165215;
			
			// aapt resource value: 0x7f070026
			public const int c26 = 2131165222;
			
			// aapt resource value: 0x7f07002b
			public const int c27 = 2131165227;
			
			// aapt resource value: 0x7f070032
			public const int c28 = 2131165234;
			
			// aapt resource value: 0x7f070039
			public const int c29 = 2131165241;
			
			// aapt resource value: 0x7f070052
			public const int c3 = 2131165266;
			
			// aapt resource value: 0x7f070058
			public const int c4 = 2131165272;
			
			// aapt resource value: 0x7f07005f
			public const int c5 = 2131165279;
			
			// aapt resource value: 0x7f070064
			public const int c6 = 2131165284;
			
			// aapt resource value: 0x7f07006b
			public const int c7 = 2131165291;
			
			// aapt resource value: 0x7f070070
			public const int c8 = 2131165296;
			
			// aapt resource value: 0x7f070075
			public const int c9 = 2131165301;
			
			// aapt resource value: 0x7f070046
			public const int d = 2131165254;
			
			// aapt resource value: 0x7f070080
			public const int d11 = 2131165312;
			
			// aapt resource value: 0x7f070095
			public const int d15 = 2131165333;
			
			// aapt resource value: 0x7f07009c
			public const int d16 = 2131165340;
			
			// aapt resource value: 0x7f07004c
			public const int d2 = 2131165260;
			
			// aapt resource value: 0x7f070020
			public const int d25 = 2131165216;
			
			// aapt resource value: 0x7f07002c
			public const int d27 = 2131165228;
			
			// aapt resource value: 0x7f070033
			public const int d28 = 2131165235;
			
			// aapt resource value: 0x7f07003a
			public const int d29 = 2131165242;
			
			// aapt resource value: 0x7f070053
			public const int d3 = 2131165267;
			
			// aapt resource value: 0x7f070059
			public const int d4 = 2131165273;
			
			// aapt resource value: 0x7f070065
			public const int d6 = 2131165285;
			
			// aapt resource value: 0x7f070096
			public const int e15 = 2131165334;
			
			// aapt resource value: 0x7f07009d
			public const int e16 = 2131165341;
			
			// aapt resource value: 0x7f07004d
			public const int e2 = 2131165261;
			
			// aapt resource value: 0x7f070021
			public const int e25 = 2131165217;
			
			// aapt resource value: 0x7f07002d
			public const int e27 = 2131165229;
			
			// aapt resource value: 0x7f070034
			public const int e28 = 2131165236;
			
			// aapt resource value: 0x7f07003b
			public const int e29 = 2131165243;
			
			// aapt resource value: 0x7f07005a
			public const int e4 = 2131165274;
			
			// aapt resource value: 0x7f070066
			public const int e6 = 2131165286;
			
			// aapt resource value: 0x7f070009
			public const int imageView1 = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int rbtnFemale = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int rbtnMale = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int rdgrp = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int rel = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int textView2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textView3 = 2131165187;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int First = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fourth = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Last = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Questions = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Second = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Third = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int dialog_animation = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
